name: koumatsumoto/publish-github-packages-npm
description: The GitHub Action to publish npm packages to GitHub Packages registry.

inputs:
  version:
    description: "Version of npm package"
    required: true
  auth_token:
    description: "Pass secrets.GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure .npmrc to deploy GitHub Packages
      shell: bash
      # .npmrcが読まれる際は、${VAR_NAME}の形式の文字列を実行時の環境変数の値で置換してくれる
      run: |
        cat << EOF > .npmrc
        @koumatsumoto:registry=https://npm.pkg.github.com/
        //npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}
        EOF

    - name: Publish package
      shell: bash
      run: npm version --no-commit-hooks --no-git-tag-version --allow-same-version ${{ inputs.version }} && npm publish --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth_token }}

    - uses: koumatsumoto/get-npm-package-info-action@v1
      id: package_info

    - name: Create Job Summary
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.auth_token }}
        script: |
          const heading = 'New GitHub Packages'
          const output = `
            *New Version* 🤖 *${{ inputs.version }}*\n
            Run command below to install newly published package.\n
            \`npm install ${{ steps.package_info.outputs.package_name }}@${{ steps.package_info.outputs.package_version }}\`\n
          `;
          await core.summary
            .addHeading(heading)
            .addRaw(output)
            .write()
